/**
 * Auto-generated API implementations
 * This file is automatically generated based on your API dependencies.
 * Do not edit manually - changes will be overwritten.
 */

import { Agent } from '@greaseclaw/workflow-sdk';

export interface GoofishApiResponse {
  success: boolean;
  error?: string;
  task?: {
    id: string;
    status: string;
    extract_data?: string;
    metrics_tokens: number;
    metrics_time: number;
  };
}

/**
 * WorkflowApis interface - methods generated from your API dependencies
 */
export interface WorkflowApis {
  login: (username: string, password: string) => Promise<GoofishApiResponse>;
  check_login: () => Promise<GoofishApiResponse>;
  get_message: (goods_url: string) => Promise<GoofishApiResponse>;
  search: (querystring: string) => Promise<GoofishApiResponse>;
  inquire: (goods_url: string, message: string) => Promise<GoofishApiResponse>;
  payment: (goods_url: string) => Promise<GoofishApiResponse>;
  send_hello_in_goofish_chat: () => Promise<GoofishApiResponse>;
}


/**
 * Creates API client using agent.call()
 */
export function createWorkflowApis(agent: Agent): WorkflowApis {
  return {
  /**
   * Login
   * Login
   * @endpoint /v1/custom/login
   */
  async login(username: string, password: string): Promise<GoofishApiResponse> {
    const { data } = await agent.call<GoofishApiResponse>('/v1/custom/login', {
      method: 'POST',
      body: { username, password },
    });
    return data;
  },

  /**
   * Check Login
   * Check Login
   * @endpoint /v1/custom/check_login
   */
  async check_login(): Promise<GoofishApiResponse> {
    const { data } = await agent.call<GoofishApiResponse>('/v1/custom/check_login', {
      method: 'POST',
    });
    return data;
  },

  /**
   * Get Message
   * Get Message
   * @endpoint /v1/custom/get_message
   */
  async get_message(goods_url: string): Promise<GoofishApiResponse> {
    const { data } = await agent.call<GoofishApiResponse>('/v1/custom/get_message', {
      method: 'POST',
      body: { goods_url },
    });
    return data;
  },

  /**
   * Search
   * Search
   * @endpoint /v1/custom/search
   */
  async search(querystring: string): Promise<GoofishApiResponse> {
    const { data } = await agent.call<GoofishApiResponse>('/v1/custom/search', {
      method: 'POST',
      body: { querystring },
    });
    return data;
  },

  /**
   * Inquire
   * Inquire
   * @endpoint /v1/custom/inquire
   */
  async inquire(goods_url: string, message: string): Promise<GoofishApiResponse> {
    const { data } = await agent.call<GoofishApiResponse>('/v1/custom/inquire', {
      method: 'POST',
      body: { goods_url, message },
    });
    return data;
  },

  /**
   * Payment
   * Payment
   * @endpoint /v1/custom/payment
   */
  async payment(goods_url: string): Promise<GoofishApiResponse> {
    const { data } = await agent.call<GoofishApiResponse>('/v1/custom/payment', {
      method: 'POST',
      body: { goods_url },
    });
    return data;
  },

  /**
   * Send Hello In Goofish Chat
   * 进入闲鱼商品详情页，点击“聊一聊”，点击后会进入聊天页面，在消息输入框中输入“你好”，并发送。
   * @endpoint /v1/custom/send_hello_in_goofish_chat
   */
  async send_hello_in_goofish_chat(): Promise<GoofishApiResponse> {
    const { data } = await agent.call<GoofishApiResponse>('/v1/custom/send_hello_in_goofish_chat', {
      method: 'POST',
    });
    return data;
  },
  };
}
