/**
 * Auto-generated API implementations
 * This file is automatically generated based on your API dependencies.
 * Do not edit manually - changes will be overwritten.
 */

import { Agent } from '@greaseclaw/workflow-sdk';

/**
 * Task status type
 */
export type TaskStatus = 'waiting' | 'running' | 'succeeded' | 'failed';

/**
 * Execution result returned by all API calls
 */
export interface ExecutionResult {
  success: boolean;
  error?: string;
  task?: {
    id: string;
    status: TaskStatus;
    extract_data?: string;
    metrics_tokens: number;
    metrics_time: number;
  };
}

/**
 * WorkflowApis interface - methods generated from your API dependencies
 */
export interface WorkflowApis {
  check_login: () => Promise<ExecutionResult>;
  get_message: (goods_url: string) => Promise<ExecutionResult>;
  search: (querystring: string) => Promise<ExecutionResult>;
  login: (username: string, password: string) => Promise<ExecutionResult>;
  payment: (goods_url: string) => Promise<ExecutionResult>;
  inquire: (goods_url: string, message: string) => Promise<ExecutionResult>;
}


/**
 * Creates API client using agent.call()
 */
export function createWorkflowApis(agent: Agent): WorkflowApis {
  return {
  /**
   * Check Login
   * Check Login
   * @endpoint /v1/custom/check-login-m98qi9
   */
  async check_login(): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/check-login-m98qi9', {
      method: 'POST',
    });
    return data;
  },

  /**
   * Get Message
   * Get Message
   * @endpoint /v1/custom/get-message-8o1vdh
   */
  async get_message(goods_url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/get-message-8o1vdh', {
      method: 'POST',
      body: { goods_url },
    });
    return data;
  },

  /**
   * Search
   * Search
   * @endpoint /v1/custom/search-wb7yqg
   */
  async search(querystring: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/search-wb7yqg', {
      method: 'POST',
      body: { querystring },
    });
    return data;
  },

  /**
   * Login
   * Login
   * @endpoint /v1/custom/login-unbav4
   */
  async login(username: string, password: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/login-unbav4', {
      method: 'POST',
      body: { username, password },
    });
    return data;
  },

  /**
   * Payment
   * Payment
   * @endpoint /v1/custom/payment-hsv65e
   */
  async payment(goods_url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/payment-hsv65e', {
      method: 'POST',
      body: { goods_url },
    });
    return data;
  },

  /**
   * Inquire
   * Inquire
   * @endpoint /v1/custom/inquire-qioe4s
   */
  async inquire(goods_url: string, message: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/inquire-qioe4s', {
      method: 'POST',
      body: { goods_url, message },
    });
    return data;
  },
  };
}
